In [1]:
import numpy as np


In [2]:
A= np.array([
            [0,1,-1],
            [1,2,3],
            [2,1,0],
            [-1,2,-4]
            ])

In [8]:
A[1][1]

2

In [9]:
A=np.array([
    [3, 1],
    [2, 3]
])

In [10]:
5*A

array([[15,  5],
       [10, 15]])

In [12]:
A=np.array([
    [1,3,1],
    [2,2,1]
])
B=np.array([
    [5,6],
    [4,2],
    [3,1]
])

In [17]:
A.shape, B.shape

((2, 3), (3, 2))

In [16]:
A@B

array([[20, 13],
       [21, 17]])

In [23]:
A=np.array([
    [1,-1,2],
    [3,2,2] 
])
B=np.array([
    [0,1],
    [-1,1],
    [5,2]
])
C=np.array([
    [2,-1],
    [-3,3]
])
D=np.array([
    [-5,1],
    [2,0]
])

In [24]:
2*A@-B@(3*C+D)

array([[  34,  -28],
       [ 110, -130]])

In [25]:
2*A@(-B)@(3*C+D)

array([[  34,  -28],
       [ 110, -130]])